version: '3.9'
services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: armazem
    ports:
      - "5433:5432"
    healthcheck:
      interval: 30s
      timeout: 10s
  
  java_jwt:
    container_name: gabi-teste-api
    image: gabi-teste-api
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_URL: "postgresql://postgresql:5432/armazem?createDatabaseIfNotExist=true&sslmode=disable&useTimezone=true&serverTimezone=UTC"
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    restart: on-failure